language: generic

sudo: required
dist: trusty

before_install:
    - sudo apt-get install -q python python-pip
    - sudo pip install -q flake8
    - nvm install stable
    - npm install -q -g eslint eslint-config-wikimedia

script:
    - find . -name \*.py -exec flake8 {} \;
    - find . -name \*.js | grep -v min.js | xargs eslint
